// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2026, 9:36:35 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Jacob/homework/jacob-dev/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/plugins/**/*.{js,ts,mjs}","C:/Users/Jacob/homework/jacob-dev/composables/**/*.{js,ts,mjs}","C:/Users/Jacob/homework/jacob-dev/utils/**/*.{js,ts,mjs}","C:/Users/Jacob/homework/jacob-dev/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Jacob/homework/jacob-dev/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;