import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface HomeCollectionItem extends DataCollectionItemBase {
    title: string;
    subtitle: string;
    bio: string;
    stack: string[];
    awards: {
    title: string;
    year: string;
    }[];
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface WorkCollectionItem extends PageCollectionItemBase {
    title: string;
    tags: string[];
    order: number;
    description: string;
    published: boolean;
    date: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface BlogCollectionItem extends PageCollectionItemBase {
    title: string;
    tags: string[];
    order: number;
    date: string;
    description: string;
    published: boolean;
  }
  

  interface PageCollections {
    work: WorkCollectionItem
    blog: BlogCollectionItem
  }

  interface Collections {
    home: HomeCollectionItem
    work: WorkCollectionItem
    blog: BlogCollectionItem
  }
}
